name: Go

on:
  push:
    branches: [ "main" ]
    paths: 
      '**/*.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
    - name: Run go vet
      run: go vet ./...
    - name: Checkout with golangci-lint
      uses: golangci/golangci-lint-action@latest
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: oysterio/final-main
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 